{% set name = "laz-perf" %}
{% set version = "1.5.0" %}
{% set sha256 = "75f007e18ddc8cec8c21c641c2c25ce668bcd67f0ee8cf4ebad1c740a4e21b70" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/hobu/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win and py!=36]

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
  run:

test:
  commands:
    - test -d ${PREFIX}/include/laz-perf  # [not win]
    - if not exist %LIBRARY_INC%\\laz-perf exit 1  # [win]

about:
  home: https://github.com/hobu/laz-perf
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: COPYING
  summary: Alternative LAZ implementation for C++ and JavaScript
  description: |
    Alternative LAZ implementation for C++ and JavaScript..
  doc_url: https://github.com/hobu/laz-perf
  dev_url: https://github.com/hobu/laz-perf

extra:
  recipe-maintainers:
    - chambbj
    - hobu
