{% set name = "laz-perf" %}
{% set version = "2.0.0" %}
{% set sha256 = "0b088e17b7ed96333fc4d791fb78d021e37a63c97fe85dff59b19a0098df6462" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/hobu/{{ name }}.git
  git_rev: updatetest

build:
  number: 0
  skip: true  # [win and py!=36]

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
  run:

test:
  commands:
    - test -d ${PREFIX}/include/lazperf  # [not win]
    - if not exist %LIBRARY_INC%\\lazperf exit 1  # [win]

about:
  home: https://github.com/hobu/laz-perf
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: COPYING
  summary: Alternative LAZ implementation for C++ and JavaScript
  description: |
    Alternative LAZ implementation for C++ and JavaScript..
  doc_url: https://github.com/hobu/laz-perf
  dev_url: https://github.com/hobu/laz-perf

extra:
  recipe-maintainers:
    - chambbj
    - hobu
