# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "LWqXV2K6DN3kIiVMEXbhUDL3BEPHpK5BgykyYJDa1Fkg82ZLCa6wdOpUZ2fTRwXmUUs5EzRz/AmqXKxkL24G5qNHLNpmEskyl9X62l0Ku/VlY7vUUbMTxjR/MX4zpPMS0qk/wMv7xyRv5VSqZbFi0RIE9KnywuJiifB9xbBAtTIAXT88Y/awYMztL7Q7cLBUOCe7MDB4GiGVvvRr2fJWduhO9Trlx5LXoKaiVUQ70MeYepfKLjz+deJeFI39xVTmVJzR+tmgadgRilRk9zc1MI2rrJjg5VxKCluLcEXX4zPnPMVfoG7w6rwIavt1uYoMJ2lp8eKklAgrofFPPLagaylebZKy9wzhF6kbtrjdC3Zq5yl5RGmHfZuoyTyb4dbRT10ZEEN9H7k1HvcVp7YOwTXIKuBqf2iiJ5cbbjwNkCDvPPbyw9dKHHGc+rnYjReSFBUDTnZ/KxWD8buiEBDlFt0fVcUopHAL5L55hyIc9cpNj21s7qK12TuFoXIzG02d4zd99Bb7JwglHa9fmHv/CNv8UBXpEnZH6/In2N1Z0wBPk52QSGpJQ4FVpQYJElgQEAXux9G+OQP53P/9nABF513ROaWfegJ4CLAxm9iRm5N2ZHmMmd72D158EnJl4ZL5lwpaZWahd/Bx3iWNA9O2IQlHVlKeEoM3XxYQWyjg8CE="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
