appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: ffFvagi/CHmyeDUbNJDa9V86WklBSRVPJKd62k1xx6qsAimojOxUsUHEWbLkR8Relr09Ix4n3hxWPVoYE43jbV8cgHCLAieKAoNL5Yxq8vjO5raKgxykpcWwjInOf+rslUey0jLtiWyL6hP8rclV54ESOcMxHxUZf1BHJ35G2BS8V2Ckgkm9AJPAo8o9WJDXzw+cSI3CaWnRs6gKObgONV1Nj/O18O/PGR3QQXEq8q/Z8PkHU68alumuD0QydjyQWTOSd3Nq6wgl4BqcKUFtuKavr9CIg2l72im0uaDZjV9IMVV+a10KcDRDCTZaoZ6FS7ZvCG2Z4ijpI4JKShhKDu+tPKvPP3YQZIHGOX0w9qubDkTIMk7vqtZEY1wqYea94JhAlMJ8DrCy/UU6va2EZpP6gJHjQ2oQBaLqPPzINCidAB5COONACn1DiLIrMuSI7nDqKWWNgspR+AVqQl05bpXBPWgp5ywFzYKbwndFjT18wuD8/u9MrT99LurfkXjfiQQ195c1s9Iem7pXqCRT3KdVElpV6umucLmF5RqHHAdpm2XmDc0x9RWTFcFy06+8sDPxM+fMPfjQXzPBIMxHAz9O646f2vw5qH7AbrNjutJPwaw1GhyZSogRreq88FRo+YubG6e97CwuTpktXawxP55qi6Tv4s8wi8Q7jhP14Po=}
provider:
  win: azure
conda_forge_output_validation: true
